# Generated by Django 5.1.2 on 2024-12-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media_uploads/blogs/')),
                ('title', models.CharField(max_length=350)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='team.team')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
